### ISSUE TITLE
bundler: failed to load command: puma

### ISSUE THREAD

**Issue by supercaracal** [supercaracal/aniwatch#2]
```
Puma starting in single mode...
* Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
* Min threads: 1, max threads: 1
* Environment: production
* Listening on tcp://0.0.0.0:80
bundler: failed to load command: puma (/home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/bin/puma)
```

Error reason is nothing.

```
$ service puma status
● puma.service - LSB: Puma web server
   Loaded: loaded (/etc/init.d/puma; generated; vendor preset: enabled)
   Active: active (exited) since 土 2016-11-12 16:25:52 JST; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 11497 ExecStop=/etc/init.d/puma stop (code=exited, status=0/SUCCESS)
  Process: 11524 ExecStart=/etc/init.d/puma start (code=exited, status=0/SUCCESS)

11月 12 16:25:52 aniwatch systemd[1]: Starting LSB: Puma web server...
11月 12 16:25:52 aniwatch puma[11524]:  * => Running the jungle...
11月 12 16:25:52 aniwatch puma[11524]:  * --> Woke up puma /home/kasuga/vcs/aniwatch
11月 12 16:25:52 aniwatch puma[11524]:  * user kasuga
11月 12 16:25:52 aniwatch puma[11524]:  * log to /home/kasuga/vcs/aniwatch/log/puma.log
11月 12 16:25:52 aniwatch puma[11524]:  * environment RAILS_ENV='production'
11月 12 16:25:52 aniwatch puma[11524]:  * environment PORT=80
11月 12 16:25:52 aniwatch puma[11524]:  * environment RAILS_MAX_THREADS=1
11月 12 16:25:52 aniwatch puma[11524]:  * environment PATH="/home/kasuga/.ndenv/shims:$PATH"
11月 12 16:25:52 aniwatch systemd[1]: Started LSB: Puma web server.
```

**Comment by supercaracal** [comment]
```
$ RAILS_ENV=production PORT=80 RAILS_MAX_THREADS=1 PATH="/home/kasuga/.ndenv/shims:$PATH" run-puma /home/kasuga/vcs/aniwatch /home/kasuga/vcs/aniwatch/config/puma.rb /home/kasuga/vcs/aniwatch/log/puma.log
Errno::EACCES: Permission denied - bind(2) for "0.0.0.0" port 80
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `initialize'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `new'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:266:in `add_tcp_listener'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:102:in `block in parse'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `each'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/binder.rb:85:in `parse'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/runner.rb:133:in `load_and_bind'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/single.rb:85:in `run'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/cli.rb:74:in `run'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/gems/puma-3.6.0/bin/puma:10:in `<top (required)>'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/bin/puma:23:in `load'
  /home/kasuga/vcs/aniwatch/.bundle/ruby/2.3.0/bin/puma:23:in `<top (required)>'
```

**Comment by supercaracal** [comment]
| Server | Port |
| --- | --- |
| nginx | 80 |
| puma | 3000 |

```
$ cat /etc/nginx/sites-available/default
server {
  listen 80 default_server;
  listen [::]:80 default_server;

  root /home/kasuga/vcs/aniwatch/public;
  server_name aniwatch.japaneast.cloudapp.azure.com;

  keepalive_timeout 5;

  location / {
    proxy_pass http://localhost:3000;
  }
}
```
